// THIS FILE WAS GENERATED BY 'go generate' - DO NOT EDIT BY HAND!

package main

import (
	"github.com/tetratelabs/wazero"
)

func exportPlatform(b wazero.HostModuleBuilder) {
	b.NewFunctionBuilder().WithFunc(PlatformSetWindowSize).Export("PlatformSetWindowSize")
	b.NewFunctionBuilder().WithFunc(wasmLog).Export("PlatformLog")
	b.NewFunctionBuilder().WithFunc(PlatformExit).Export("PlatformExit")
	b.NewFunctionBuilder().WithFunc(PlatformFps).Export("PlatformFps")
	b.NewFunctionBuilder().WithFunc(PlatformTps).Export("PlatformTps")
}

func exportInput(b wazero.HostModuleBuilder) {
	b.NewFunctionBuilder().WithFunc(wasmUp).Export("InputUp")
	b.NewFunctionBuilder().WithFunc(wasmDown).Export("InputDown")
	b.NewFunctionBuilder().WithFunc(wasmPressed).Export("InputPressed")
	b.NewFunctionBuilder().WithFunc(InputCursorX).Export("InputCursorX")
	b.NewFunctionBuilder().WithFunc(InputCursorY).Export("InputCursorY")
}

func exportGfx(b wazero.HostModuleBuilder) {
	b.NewFunctionBuilder().WithFunc(GfxSetTargetSize).Export("GfxSetTargetSize")
	b.NewFunctionBuilder().WithFunc(wasmClear).Export("GfxClear")
	b.NewFunctionBuilder().WithFunc(GfxTexture).Export("GfxTexture")
	b.NewFunctionBuilder().WithFunc(wasmTextureEx).Export("GfxTextureEx")
	b.NewFunctionBuilder().WithFunc(wasmCircle).Export("GfxCircle")
	b.NewFunctionBuilder().WithFunc(wasmRectangle).Export("GfxRectangle")
	b.NewFunctionBuilder().WithFunc(wasmDefaultText).Export("GfxDefaultText")
}

func exportAsset(b wazero.HostModuleBuilder) {
	b.NewFunctionBuilder().WithFunc(wasmLoadImage).Export("AssetLoadImage")
}

func exportConfig(b wazero.HostModuleBuilder) {
	b.NewFunctionBuilder().WithFunc(ConfigSetFlags).Export("ConfigSetFlags")
}


// This ensures each api fits what wasm expects
var (
	_ = platform{
		SetWindowSize: PlatformSetWindowSize,
		Log: PlatformLog,
		Exit: PlatformExit,
		Fps: PlatformFps,
		Tps: PlatformTps,
	}
	_ = input{
		Up: InputUp,
		Down: InputDown,
		Pressed: InputPressed,
		CursorX: InputCursorX,
		CursorY: InputCursorY,
	}
	_ = gfx{
		SetTargetSize: GfxSetTargetSize,
		Clear: GfxClear,
		Texture: GfxTexture,
		TextureEx: GfxTextureEx,
		Circle: GfxCircle,
		Rectangle: GfxRectangle,
		DefaultText: GfxDefaultText,
	}
	_ = asset{
		LoadImage: AssetLoadImage,
	}
	_ = config{
		SetFlags: ConfigSetFlags,
	}
)

	