// Code generated by 'go generate ./...'; DO NOT EDIT.
package engine

import (
	"context"
	"github.com/tetratelabs/wazero/api"
)

func (a *Asset) Expose(wasm *WasmRuntime) {
	wasm.ConvertAndExpose("AssetLoadTexture", a.LoadTexture, wasmLoadTexture)

}

// Wasm wrappers for Asset

// Calls Asset.LoadTexture
func wasmLoadTexture(ctx context.Context, m api.Module, stack []WasmValue) {
	arg0_0 := api.DecodeU32(stack[0])
	arg0_1 := api.DecodeU32(stack[1])
	r0 := brut.Asset.LoadTexture(
		readWasmString(m.Memory(), arg0_0, arg0_1),
	)
	stack[0] = api.EncodeU32(uint32(r0))
}
