// Code generated by 'go run generate.go'; DO NOT EDIT.
package brutengine_go

// Enums

type EngineFlag uint32

const (
	EngineFlagHotReload        EngineFlag = 1
	EngineFlagLogging          EngineFlag = 4
	EngineFlagSetupAfterReload EngineFlag = 2
)

type InputEvent uint32

const (
	InputEventEnter       InputEvent = 3
	InputEventEscape      InputEvent = 2
	InputEventMouseLeft   InputEvent = 8
	InputEventMouseMiddle InputEvent = 9
	InputEventMouseRight  InputEvent = 10
	InputEventSpace       InputEvent = 4
	InputEventBackspace   InputEvent = 5
)

type Texture uint32

// Structs

type Color struct {
	C1 float32
	C2 float32
	C3 float32
	C4 float32
}

// Config Api
//
//go:export ConfigGetEngineFlags
func ConfigGetEngineFlags() EngineFlag

//go:export ConfigSetEngineFlags
func ConfigSetEngineFlags(EngineFlag)

// Platform Api
//
//go:export PlatformExit
func PlatformExit()

//go:export PlatformFps
func PlatformFps() float32

//go:export PlatformLog
func PlatformLog(string)

//go:export PlatformSetScreenSize
func PlatformSetScreenSize(int32, int32)

//go:export PlatformSetTitle
func PlatformSetTitle(string)

//go:export PlatformTps
func PlatformTps() float32

// Input Api
//
//go:export InputCursorX
func InputCursorX() float32

//go:export InputCursorY
func InputCursorY() float32

//go:export InputDown
func InputDown(InputEvent) bool

//go:export InputPressed
func InputPressed(InputEvent) bool

//go:export InputUp
func InputUp(InputEvent) bool

// Graphics Api
//
//go:export GraphicsCircle
func GraphicsCircle(float32, float32, float32, float32, float32, float32, float32, bool)

//go:export GraphicsClear
func GraphicsClear(float32, float32, float32, float32)

//go:export GraphicsRectangle
func GraphicsRectangle(float32, float32, float32, float32, float32, float32, float32, float32, bool)

//go:export GraphicsSetTargetSize
func GraphicsSetTargetSize(int32, int32)

//go:export GraphicsText
func GraphicsText(string, float32, float32)

//go:export GraphicsTexture
func GraphicsTexture(Texture, float32, float32)

//go:export GraphicsTextureEx
func GraphicsTextureEx(Texture, float32, float32, float32, float32, float32, float32, float32, float32, float32)

// Asset Api
//
//go:export AssetLoadTexture
func AssetLoadTexture(string) Texture
